[package]
name = "shuttle-game-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
shuttle-axum = "0.53.0"
shuttle-runtime = "0.53.0"
tokio = "1.44.1"
tower-http = { version = "0.6.2", features = ["fs"] }